import type { Place, Scenario } from "./types";

export const scenarioLabels: Record<Scenario, string> = {
  date: "Date",
  friends: "Bạn bè",
  food: "Ăn uống",
  coffee: "Cafe",
  fun: "Vui chơi",
  chill: "Chill"
};

export const places: Place[] = [
  {
    id: "lake-house",
    name: "The Lake House",
    kind: "Cafe · Bistro",
    description: "Không gian cạnh hồ, nhiều bàn ngoài trời và hợp ngồi nói chuyện.",
    latitude: 21.0551,
    longitude: 105.8194,
    distanceKm: 1.2,
    priceLabel: "$$",
    averageForTwo: "250–350k / 2 người",
    publicRating: 4.7,
    match: 94,
    communityNote: "6/7 người sẽ quay lại",
    openUntil: "23:00",
    bestTime: "19:00–22:00",
    noise: "Yên",
    crowd: "Vừa",
    tags: ["Date", "Nói chuyện", "Buổi tối", "View hồ"],
    scenarios: ["date", "coffee", "chill"],
    note: "Đi tối đẹp hơn, bàn phía hồ yên hơn.",
    accent: "#ff6b5e"
  },
  {
    id: "kohi-garden",
    name: "Kohi Garden",
    kind: "Cafe",
    description: "Nhiều cây xanh, ánh sáng dịu và góc ngồi riêng vừa đủ.",
    latitude: 21.0365,
    longitude: 105.803,
    distanceKm: 1.8,
    priceLabel: "$$",
    averageForTwo: "180–280k / 2 người",
    publicRating: 4.6,
    match: 89,
    communityNote: "5/6 người sẽ quay lại",
    openUntil: "22:30",
    bestTime: "16:30–20:30",
    noise: "Yên",
    crowd: "Vừa",
    tags: ["Cafe", "Chill", "Nói chuyện", "Cây xanh"],
    scenarios: ["date", "coffee", "chill"],
    note: "Cuối tuần nên đến sớm để có góc đẹp.",
    accent: "#6f9274"
  },
  {
    id: "nang-rooftop",
    name: "Nắng Rooftop",
    kind: "Rooftop",
    description: "View thành phố, hợp đi tối và nhóm nhỏ thích không khí thoáng.",
    latitude: 21.0185,
    longitude: 105.825,
    distanceKm: 2.4,
    priceLabel: "$$$",
    averageForTwo: "380–520k / 2 người",
    publicRating: 4.5,
    match: 86,
    communityNote: "4/5 người sẽ quay lại",
    openUntil: "00:00",
    bestTime: "18:30–22:30",
    noise: "Vừa",
    crowd: "Đông",
    tags: ["Rooftop", "Buổi tối", "Date", "View đẹp"],
    scenarios: ["date", "friends", "chill"],
    note: "Đẹp lúc hoàng hôn, sau 21h nhạc sẽ lớn hơn.",
    accent: "#6677a8"
  },
  {
    id: "hero-bowling",
    name: "Hero Bowling",
    kind: "Activity",
    description: "Hoạt động dễ chơi cho nhóm, không cần chuẩn bị trước.",
    latitude: 20.9952,
    longitude: 105.8146,
    distanceKm: 2.8,
    priceLabel: "$$",
    averageForTwo: "280–420k / 2 người",
    publicRating: 4.6,
    match: 92,
    communityNote: "7/8 người sẽ quay lại",
    openUntil: "23:30",
    bestTime: "19:00–22:30",
    noise: "Sôi động",
    crowd: "Vừa",
    tags: ["Vui chơi", "Đi nhóm", "Buổi tối"],
    scenarios: ["friends", "fun"],
    note: "Nhóm 4–6 người là vui nhất.",
    accent: "#6c63d9"
  },
  {
    id: "mot-quan-nho",
    name: "Một Quán Nhỏ",
    kind: "Bistro · Cafe",
    description: "Quán nhỏ, ấm và ít bàn; hợp một buổi nói chuyện dài.",
    latitude: 21.0118,
    longitude: 105.8458,
    distanceKm: 1.1,
    priceLabel: "$",
    averageForTwo: "160–240k / 2 người",
    publicRating: 4.3,
    match: 82,
    communityNote: "4/5 người sẽ quay lại",
    openUntil: "22:00",
    bestTime: "17:00–20:00",
    noise: "Yên",
    crowd: "Vắng",
    tags: ["Ăn uống", "Cafe", "Yên tĩnh"],
    scenarios: ["date", "food", "coffee"],
    note: "Bàn ít nhưng không gian rất dễ nói chuyện.",
    accent: "#b07b62"
  },
  {
    id: "sushi-x",
    name: "Sushi X",
    kind: "Restaurant",
    description: "Quán ăn nhỏ, menu vừa đủ và phục vụ nhanh.",
    latitude: 21.0252,
    longitude: 105.8508,
    distanceKm: 2.1,
    priceLabel: "$$$",
    averageForTwo: "420–650k / 2 người",
    publicRating: 4.5,
    match: 88,
    communityNote: "5/7 người sẽ quay lại",
    openUntil: "22:30",
    bestTime: "18:00–20:30",
    noise: "Vừa",
    crowd: "Đông",
    tags: ["Ăn tối", "Date", "Nhóm nhỏ"],
    scenarios: ["date", "friends", "food"],
    note: "Nên đặt bàn trước vào tối cuối tuần.",
    accent: "#d68d4f"
  }
];
