/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js tooling expectations.
// Do not edit unless the framework migration guide explicitly requires it.
